---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:17.4
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: lidarr-secret
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/home-operations/lidarr
      tag: 2.14.3.4791
    env:
      TZ: America/Chicago
      LIDARR__INSTANCE_NAME: Lidarr
      LIDARR__PORT: &port 8686
      LIDARR__APPLICATION_URL: "https://{{ .Release.Name }}.kalde.in"
      LIDARR__LOG_LEVEL: info
    envFrom: *envFrom
    service:
      main:
        ports:
          http:
            port: *port
    probes:
      liveness: &probes
        enabled: false
        custom: true
        spec:
          httpGet:
            path: /ping
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: "{{ .Release.Name }}.kalde.in"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "{{ .Release.Name }}.kalde.in"
    podSecurityContext:
      runAsUser: 1024
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/lidarr
        mountPath: /config
      media:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume2/share/music
        mountPath: /music
      downloads:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/downloads/complete/music
        mountPath: /downloads
      backup:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/backup/lidarr
    resources:
      requests:
        cpu: 2
        memory: 2000Mi
      limits:
        cpu: 2
        memory: 4000Mi
#    affinity:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#            - matchExpressions:
#                - key: node-role.kubernetes.io/master
#                  operator: DoesNotExist
#            - matchExpressions:
#                - key: node-role.kubernetes.io/control-plane
#                  operator: DoesNotExist
